import { join } from "path";
import { cp, readdir } from "fs/promises";
import { fileURLToPath } from "url";
import { dirname } from "path";
import globals from "./globals.js";
import { MKDir, WriteFile } from "./Toolkit/fileIO.mod.js";
import NPMQueue from "./queue/NPM.queue.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

export default async () => {
  const tarPath = join(process.cwd(), globals.projectname);
  const typeExt = globals.projecttype === "javascript" ? "js" : "ts";

  // 創建項目文件結構
  const README = `# ${globals.projectname}

Generated by ks3-toolkit v2.2.7

## Getting Started

This project was generated with the ks3-toolkit, which provides common utilities for:
- Database operations (MariaDB/MySQL)
- File I/O operations
- Date/time conversions
- HTTP requests (GET, POST, PUT, DELETE)
- XML parsing
- Command execution
- CLI argument parsing

## Scripts

\`\`\`bash
npm start          # Start the project
npm run build      # Build the project (TypeScript only)
npm test           # Run tests
\`\`\`

## License

Apache 2.0
`;

  console.log(`📁 Creating project structure at: ${tarPath}`);
  await MKDir(join(tarPath, "src", "toolkit"));
  await WriteFile(join(tarPath, "src", `index.${typeExt}`), helloworld);
  await WriteFile(join(tarPath, "README.md"), README);

  // 複製工具模塊
  console.log("📦 Copying toolkit modules...");
  const source = join(__dirname, "Toolkit");
  const filenames = await readdir(source);

  for (const name of filenames) {
    // js時複製.d.ts聲明文件，否則複製相應語言的源文件
    if (
      (typeExt === "js" && name.includes(".d.")) ||
      (name.endsWith(typeExt) && !name.includes(".d."))
    ) {
      await cp(join(source, name), join(tarPath, "src", "toolkit", name))
        .catch(() => {
          // 如果複製失敗，忽略並繼續
        })
        .finally(() => {
          console.log(`✓ Copied: ${name}`);
        });
    }
  }

  // NPM 初始化和依賴安裝
  console.log("📦 Installing npm packages...");
  await NPMQueue();

  // 複製基礎配置文件
  console.log("📋 Copying configuration files...");
  const dataSource = join(__dirname, "../", "../", "src", "data");
  const dataFilenames = await readdir(dataSource);

  for (const name of dataFilenames) {
    await cp(join(dataSource, name), join(tarPath, name))
      .catch(() => {
        // 文件可能已存在，忽略錯誤
      })
      .finally(() => {
        console.log(`✓ Copied: ${name}`);
      });
  }
};

const helloworld = `${
  globals.projecttype === "javascript"
    ? `import './toolkit/date.func.js';\n`
    : ""
}
// 歡迎使用 ks3-toolkit！
console.log('✨ Hello from ks3-toolkit!');
console.log('📅 Current datetime:', new Date().convertToDateTime());

// 由於這是一個生成的項目範本，您可以根據需要修改此文件。
// Try:
// - Database operations from ./toolkit/dbhandler
// - File operations from ./toolkit/fileIO.mod
// - HTTP requests from ./toolkit/http.mod
// - And more toolkit utilities...
`;
