name: Publish to NPM Packages

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'
      - name: Remove publishConfig from package.json
        run: |
          jq 'del(.publishConfig)' package.json > temp.json && mv temp.json package.json
      - name: Update package.json name
        run: |
          jq '.name = "${{ github.event.repository.name }}"' package.json > temp.json && mv temp.json package.json

      - name: remove .npmrc
        run: rm -f .npmrc

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run compile

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
